[build]
  publish = "public"
  command = "yarn run bootstrap && yarn run build && yarn run netlify"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.12.3"
  YARN_FLAGS = "--pure-lockfile"
